export const siteMeta = {
  title: "Quantrail | Private AI Solutions, Features, Packages, FAQ & About",
  description:
    "Quantrail delivers secure, local-first AI. Explore QOne features, deploy your private intelligence layer, validate with GPU pilots, get answers on deployment and security, and learn about our mission.",
  keywords: [
    "Quantrail",
    "Private AI infrastructure",
    "On-premise LLM",
    "Enterprise AI security",
    "Zero data harvesting",
    "Local AI deployment",
    "QOne AI suite",
    "Data ownership",
    "Private Intelligence Layer",
    "On-premise AI software",
    "Local LLM deployment",
    "Secure enterprise AI",
    "Air-gapped AI solutions",
    "IP protection for AI",
    "Self-hosted AI engine",
    "Private AI pilot",
    "B2B AI free trial",
    "GPU enabled AI software",
    "Enterprise AI deployment",
    "On-premise AI pricing",
    "Local-first AI packages",
    "Quantrail QOne pilot",
    "Secure AI integration",
    "Local AI reasoning",
    "Private document indexing",
    "Secure neural search",
    "Enterprise AI auditing",
    "Fine-grained access control AI",
    "Provider-agnostic AI deployment",
    "On-premise LLM features",
    "QOne private intelligence",
    "Quantrail features",
    "Private AI FAQ",
    "GPU hardware for AI",
    "Offline LLM deployment",
    "Quantrail QOne support",
    "Enterprise AI data protection",
    "Local AI implementation",
    "Quantrail mission",
    "On-premise AI technology",
    "Data ownership for AI",
    "Private computing enterprise",
    "Local-first AI company",
    "Secure AI deployment",
    "QOne background"
  ],
  openGraph: {
    title: "Quantrail QOne | Secure Local AI, Features, Packages, FAQ & About",
    description:
      "Run frontier AI securely on your own hardware. Explore QOne features, start with a 30-day pilot, get answers on deployment, and learn about our mission.",
    type: "website",
    url: "https://qone.quantrail-data.com",
    images: {
      url: "./og-home.png",
      width: 1200,
      height: 630,
      alt: "Quantrail QOne Private AI Solutions, Features, Packages, FAQ & About",
    },
  },
  twitter: {
    card: "summary_large_image",
    title: "Your Hardware. Your AI. Your Rules.",
    description:
      "Secure, local-first AI validation with Quantrail QOne. Explore features, pilot packages, FAQ answers, and our mission for enterprise-scale deployment.",
    images: "./og-home.png",
  },
};